### ISSUE TITLE
Translate "Hacking"

### ISSUE THREAD

**Issue by wldhx** [goto-ru/paulgraham-college#7]

**Comment by wldhx** [comment]
@danya02 May I ask for your assistance on this?

**Comment by danya02** [comment]
@wldhx I'm guessing I could try to help with the translation. What's the deadline?

EDIT: To be more specific, is the deadline farther than 16 hours?

**Comment by wldhx** [comment]
@danya02 While it'd be nice to have it done in a day (24 hours), it'll wait for two (or maybe even three).

If we have your commitment to having it done, we can start working on the Habr article in the meantime.

**Comment by danya02** [comment]
@wldhx Already started the translation. About 25% done, will soon make an intermediary commit.

**Comment by danya02** [comment]
Finished the translation, see #12.
